---
title: "international_paper"
author: "David McAllister on behalf of Research and Epidemiology Cell of PHS"
date: "09/12/2020"
output: github_document
bibliography: references.bib
csl: the-lancet.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# Introduction - paper, international context

Children are relatively protected from Severe Acute Respiratory Syndrome coronavirus 2 (SARS-CoV-2). When exposed, children are less likely to develop symptomatic infection (COVID-19), and when infected they are less like to become seriously ill.[1] This difference is large; in the UK over the peak 9 weeks of the first phase of the epidemic, the mortality in the UK population for SARS-CoV-2 was 0.0005% among children aged 0 to 14, compared to 0.003% for adults aged 25-44 and 0.11% for adults aged 65 to 74.[2] In contrast, limiting children's access to school harms their education and appears to harms their physical and mental health, particularly among children from socio-economically deprived backgrounds.

Despite this, in many areas schools have remained closed, partly due to concerns that adults who work in educational settings would be placed at increased risk of severe COVID-19 infection or even death if schools re-opened. 

Vlachos et al[@vlachos2020] compared the risk of COVID-19 test positivity, COVID-19 diagnosis and severe COVID-19 (hospitalisation and death) between upper and lower secondary school teachers, adjusting for age, sex and income and region; for all three outcomes, lower secondary school teachers, who taught in person, were at around two-fold higher risks than upper secondary school teachers who did not. Vlachos et al did not compare either group to the general population in adjusted analyses, but on comparing crude rates of PCR-positivity between occupations (after excluding healthcare workers), upper secondary school teachers were close to the median rank, whereas lower secondary were at the seventh highest risk. In contrast, a study from Stockholm compared mortality among a range of occupations (reference group IT technicians). Adjusting for age, sex, country of birth, living in Stockholm (which had the highest rates of COVID-19), highest achieved educational degree, and individual net income, teachers were not at increased risk, although the confidence intervals were wide (RR 0.91; 95% CI 0.55-1.51).

In a population-wide analysis of Norway, compared to all working-age adults, adjusting for age, sex aond country of birth, those in teaching occupations were not found to be at increased risk of COVID-19 (positive PCR and/or a diagnostic code) during the first wave. In the second wave, (July 18th to Oct 18th) during which schools were open the pattern was more complex with modestly increased risks in primary school teachers (1.14; 95% CI 0.99 - 1.32), secondary education teachers (1.10; 95% CI 0.82,1.47)and childcare workers (1.145; 95% CI 1.02,1.29) but not in "early childhood educators" (0.73; 95% CI 0.54-0.99). Taking all periods together, the risks of hospitalisation with COVID 19 varied; primary school teacher (0.73; 95% CI 0.44-1.22), Early childhood educators(1.86; 95% CI 0.97-3.57), Child care workers(1.28; 95% CI 0.90-1.81), Secondary education teachers (1.01; 95% CI 0.46-2.21) and University & higher education teachers(1.11; 95% CI 0.65-1.92).

A US survey of child-care providers which had a 69% response rate obtained retrospective data on characteristics fo the child-care facility and the provider, including whether they had ever tested positive for COVID-19 or been hospitalised with COVID-19.[@gilliam2020] On adjusting for age, sex, race, access to PPE, household income and background rates of infection there was no association between exposure to child care and risk of COVID-19 among childcare providers (OR 1.06; 0.82-1.38).

Scotland has a well established health records informatics infrastructure which can be used to link data for individuals on a range of COVID-19 outcomes as well as on underlying conditions. Furthermore, all teachers working in the state sector in Scotland are legally obliged to register with the General Teaching Council for Scotland, who hold this database centrally. Finally, schools in Scotland closed during the first wave of the COVID-19 pandenic, but have remained open throughout the second, with mask-earing being confined to secondary schools where older children (age 12-17) are taught. This combination of circumatances provided us with an opportunity to estimate the risk to teachers of a range of outcomes for COVID-19, including hospitalisation, both before and after schools closed.

# Discussion -- paper

In a Scotland-wide dataset covering the period from the first case in Scotland to the 26th of November 2020, we compared the risk of COVID-19 in teachers to that of healthcare workers and other members of the working-age population. Although teachers were more likely to test positive for SARS-CoV-2 than the general population in the period after schools re-opened, their risk of hospitalisation with COVID-19 was not increased during this period. In contrast healthcare workers did have an increased risk of hospitalisation during the period after schools re-opened. For both teachers and healthcare workers the risk of severe COVID-19 (defined where an individual was admitted to intensive care or died within 28 days of testing positive for SARS-CoV-2) was lower than that of the general working-age population; in the case of teachers the risk was considerably lower at around half, and this difference was statistically significant at the conventional level. These results are largely reassuring for teachers, and by extension other adults, working in educational settings.

Few studies have compared the risk of COVID-19 in educational staff to that of the wider community. In a survey which randomly sampled from the UK population, the Office for National Statistics (ONS) found that teachers were not more likely to test positive with COVID-19 compared to other occupations. A report from the ONS also reported that working in education was not associated with a higher risk of mortality from COVID-19 higher. A survey of US child care providers also found that those providing childcare in institutional settings were not at increased risk of COVID-19.[@gilliam2020] However, these analyses did not adjust for differences in underlying health between different teachers, and did not collect data on other important COVID-19 outcomes such as hospitalisation and admission to intensive care units. Nor did they compare risks for teachers working with children of different age-groups (eg nursery, primary and secondary ages).


Several previous studies have examined transmission of COVID-19 from adults to children, as well as the risk of COVID-19 among adults working in educational settings. A survey of US educational settings found that US child care providers were not at increased risk of COVID-19 infection compared to the background population (<https://pediatrics.aappublications.org/content/early/2020/12/04/peds.2020-031971>). A community surveillance study in England and Wales conducted by Public Health England found that children rarely tested positive for SARS-CoV-2, even when they had symptoms of acute respiratory infection; this was particularly true for younger children[<https://adc.bmj.com/content/early/2020/07/28/archdischild-2020-320042>]. Studies examining contacts of younger children with SARS-CoV-2 have also shown low rates of secondary cases, particularly in non-household settings, consistent with minimal or no transmission from children to adults.[COVID-19 in children and the role of school settings in COVID-19 transmission [Internet]. European Centre for Disease Prevention and Control. 2020 [cited 2020 Aug 10]. Available from: <https://www.ecdc.europa.eu/en/publications-data/children-and-school-settings-covid-19-transmission>] Moreover, the ONS recently reported that individuals working in education were not at increased risk of either COVID-19 infection or death where COVID-19 is included on the death certificate.[Coronavirus (COVID-19) related deaths by occupation, England and Wales - Office for National Statistics [Internet]. [cited 2020 Nov 19]. Available from: <https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/causesofdeath/bulletins/coronaviruscovid19relateddeathsbyoccupationenglandandwales/latest>, Office for National Statistics. Coronavirus (COVID-19) Infection Survey, UK: 6 November 2020 [Internet]. 2020. Available from: <https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/bulletins/coronaviruscovid19infectionsurveypilot/6november2020#analysis-of-the-number-of-school-workers-key-workers-and-other-professions-in-england-who-had-covid-19>] In a pre-print study based on a cohort of healthcare workers in Scotland, sharing a household with young children was not associated with increased risk of COVID-19 for adult healthcare workers [Wood R, Thomson EC, Galbraith R, Gribben C, Caldwell D, Bishop J, Reid M, Shah A, Templeton K, Goldberg D, Robertson C, Hutchinson S, Colhoun HM, McKeigue PM, McAllister D. Sharing a household with children and risk of COVID-19: a study of over 300,000 adults living in healthcare worker households in Scotland. medRxiv. 2020 Jan 1;2020.09.21.20196428]. Similarly, a report based on the 19 million person, general population OpenSafely cohort[Forbes H, Morton CE, Bacon S, McDonald HI, Minassian C, Brown JP, Rentsch CT, Mathur R, Schultze A, DeVito NJ, MacKenna B, Hulme WJ, Croker R, Walker AJ, Williamson EJ, Bates C, Mehrkar A, Curtis HJ, Evans D, Wing K, Inglesby P, Drysdale H, Wong AY, Cockburn J, McManus R, Parry J, Hester F, Harper S, Douglas IJ, Smeeth L, Evans SJ, Bhaskaran K, Eggo RM, Goldacre B, Tomlinson LA. Association between living with children and outcomes from COVID-19: an OpenSAFELY cohort study of 12 million adults in England. medRxiv. 2020 Nov 2;2020.11.01.20222315], during the early-stage of the pandemic in England before schools closed, those adults sharing a household with children aged 0-11 were not found to be at increased risk of COVID-19 infection or hospitalisation and were at a lower risk of death.

PARAGRAPH ON SAFETY MEASURES IN NURSERIES AND SCHOOLS AND PREFERABLY REFERENCE SOME POLICY DOCUMENTS

This current study adds a number of strengths. First, it covers an entire educational system, including all teachers working in state schools in Scotland. Seco

some points to cover

-   There is no evidence that teachers are at increased risk of hospitalisation with COVID-19, including in the period after schools re-opened. During the same period healthcare workers were at increased risk of hospitalisation with COVID-19
-   There is an increased risk of becoming a COVID-19 case for teachers during the period after schools re-opened, particularly in young male teachers
-   During the period after schools re-opened rates of testing were higher among teachers than among either healthcare workers or the general Scottish population
-   Teachers are at lower risk of severe COVID-19 than the general Scottish population including after the schools re-opened, HCWs are now at lower risk, but at the onset of the pandemic were at higher risk
-   Strength of the work is valid unbiased comparison
-   adjust for age, sex, SIMD, comorbidity etc
-   weakness will be incomplete, will be some misclassification so will not fully agree with counts based on primary data collection
-   only where there is a centrally held database of people in an occupation such as a teaching register. In particular social care data is missing
-   relevant literature - ONS, US survey, literature
-   Next steps more granular data, eg on school size and contact time, but power issues.
-   Two other separate projects within PHS - antibody survey, contact-tracing based analysis.
-   largely consistent with interim analysis based on partial data - more to follow

## Conclusion

-   Despite increased rates of testing positive, there was no increase in hospitalisation among teachers and a lower risk of severe COVID-19. Furthermore, the highest excess risk for testing positive was in the youngest individuals, who are at the lowest risk of severe outcomes when they develop symptomatic COVID-19 infection. This finding is consistent with the ONS observation that being a teacher was not associated with an increased risk of testing positive for or dying with COVID-19. Teachers need to continue to be monitored, but this finding is largely reassuring.

<https://pediatrics.aappublications.org/content/early/2020/10/16/peds.2020-031971>
